### ISSUE TITLE
Documentation - list available functions and call signatures

### ISSUE THREAD

**Issue by jotaf98** [toiaydcdyywlhzvlob/backpack#3]
Hi, thanks for the great package!

I looked through the docs but they seem a bit sparse -- namely, I didn't find a list of functions and how to call them. Other than reading the paper and/or source code, is this meant to be documented?

**Comment by fKunstner** [comment]
We're indeed still working on improving the docs. Did you find the page on [how to call an extension](http://docs.backpack.pt/en/master/main-api.html#calling-the-extension) and the [list of available extensions](http://docs.backpack.pt/en/master/extensions.html)? Those are the only "functions" provided by backpack

(This was the anonymous github repository for the submission. Let us know over on the [main repo issue section](https://github.com/f-dangel/backpack/issues) if something's wrong!)
